Generate enum types from schemas in paths
oapi-codegen/oapi-codegen pull request #654
Opened 2022-07-01 23:42 UTC by AlainODea

If defining types in the schema within the parameters, responses, or requestBody within the paths of the spec, generate enums for them.

Also gather deeply nested enums in component responses or requestBodies.

Fixes #399 #467 #513 #626

2022-07-02 01:11 UTC, AlainODea commented
In retrospect, this breaks some subtle things that don't appear to have functional impact. internal/test/strict-server/client/client.go generates internal/test/strict-server/client/client.gen.go and it ends up with this strange diff after my change (dropping a useless **Empty** type in place of **Reusableresponse**):

```diff
diff --git a/internal/test/strict-server/client/client.gen.go b/internal/test/strict-server/client/client.gen.go
index 6c02ddf..7ddcd94 100644
--- a/internal/test/strict-server/client/client.gen.go
+++ b/internal/test/strict-server/client/client.gen.go
@@ -22,8 +22,8 @@ type Example struct {
        Value *string `json:"value,omitempty"`
 }
 
-// Reusableresponse defines model for reusableresponse.
-type Reusableresponse = Example
+// Empty defines model for .
+type Empty = int
 
 // MultipleRequestAndResponseTypesTextBody defines parameters for MultipleRequestAndResponseTypes.
 type MultipleRequestAndResponseTypesTextBody = string
```

2022-07-11 08:12 UTC, jamietanna requested changes
This doesn't quite solve #626, as in this case we get a:

```go
// N200Health defines model for 200.Health.
type N200Health string
```

Whereas I'd expect a `struct`

2022-07-12 22:51 UTC, AlainODea commented
> This doesn't quite solve #626, as in this case we get a:
> 
> ```go
> // N200Health defines model for 200.Health.
> type N200Health string
> ```
> 
> Whereas I'd expect a `struct`

Good catch! I had missed that. I'll take another shot at this and see where I can get.

Thank you for the code review.

2022-07-25 19:26 UTC, jamietanna commented
@AlainODea no worries! Mind marking this as a draft?

(I've also spotted that there may be cases where we're not (in the existing code) generating enums from nested objects - I'll try and get an issue raised for it soon)

2022-09-28 16:32 UTC, discordianfish commented
Are you still working on this? Would be great to see this fixed.

2022-09-28 21:48 UTC, AlainODea commented
> Are you still working on this? Would be great to see this fixed.

I would love to. Unfortunately, my immediate need for this has passed and I'm swamped with other priorities at work.

There are a number of related PRs like Jamie's that take a more methodical approach to expanding support for types outside of schemas.

In the meantime, the best approach might be to manually or automatically transform the OpenAPI specs you need by moving things to schemas.

2026-05-01 02:25 UTC, mromaszewicz commented
Thank you for submitting this PR, @AlainODea — but we need to close it because all three cases you targeted (inline enums in path params, requestBodies, and responses) now generate correctly. Three independent fixes landed: commit `14fc88e2` (inline param enums, June 2022), commit `270581d0` (`GenerateTypesForPaths()` for response bodies, Nov 2022), and commit `81b9d952` (the Apr 2026 anonymous-schema-hoisting overhaul that feeds op-derived types into `GenerateEnums()`). A repro with the patterns from your PR generates correct named enum types.

Apologies for the long wait — your PR pointed at a real gap, even if the eventual fix took several rounds and a different shape.

2026-05-01 02:25 UTC, closed without merging